<a href="https://colab.research.google.com/github/Eun0416/2026-1-BDA/blob/main/code/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 03 과학용 컴퓨팅 패키지

## 다차원 배열 ndarray

In [296]:
import numpy as np

a = np.ndarray((2, 3))
a

array([[4.56e-315, 0.00e+000, 6.80e-310],
       [6.80e-310, 6.80e-310, 5.79e-317]])

In [297]:
import numpy as np

a = np.ndarray((3, 2), dtype=int)
a

array([[      922262693,               0],
       [137693289188400, 137693289188400],
       [137692316456048,        11712800]])

In [298]:
a = np.ndarray((3, 2), int)
a

array([[   979429433,            0],
       [481036337262, 438086664238],
       [463856468085, 416611827820]])

## 내장함수 array()

In [299]:
import numpy as np

a = np.array([1, 2, 3], dtype=int)
a

array([1, 2, 3])

In [300]:
type(a)

numpy.ndarray

In [301]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [302]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


## 문자열 자료형

In [303]:
np.array([1, 'py', 3.14]) # 동일 자료형이 되어야 하기 때문에 문자열 자료형

array(['1', 'py', '3.14'], dtype='<U32')

In [304]:
import numpy as np
unicode_array = np.array(['가나다', '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [305]:
unicode_array = np.array(['가나다라마'*7, '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라마바', '사아자'], dtype='<U32')

## numpy.arange()

In [306]:
import numpy as np

print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [307]:
import numpy as np

print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


## 배열의 모양을 바꾸는 reshape()

In [308]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [309]:
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [310]:
np.reshape(a, (3, 5)) # 원래 배열 원소가 12개 인데 원소가 15개(3, 5)라서 오류가 남

ValueError: cannot reshape array of size 12 into shape (3,5)

## 함수 linspace

In [334]:
import numpy as np
np.linspace(2, 3)

array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
       2.22, 2.24, 2.27, 2.29, 2.31, 2.33, 2.35, 2.37, 2.39, 2.41, 2.43,
       2.45, 2.47, 2.49, 2.51, 2.53, 2.55, 2.57, 2.59, 2.61, 2.63, 2.65,
       2.67, 2.69, 2.71, 2.73, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86, 2.88,
       2.9 , 2.92, 2.94, 2.96, 2.98, 3.  ])

In [335]:
(3-1)/(50-1)

0.04081632653061224

In [336]:
np.linspace(2, 3, 2)

array([2., 3.])

In [337]:
np.linspace(2, 3, 3)

array([2. , 2.5, 3. ])

In [338]:
np.linspace(2, 3, 3, retstep=True)

(array([2. , 2.5, 3. ]), np.float64(0.5))

In [339]:
a = np.linspace(2, 3, 3, retstep = True)
float(a[1])

0.5

In [340]:
np.linspace(2, 3, 3, retstep = True, endpoint=False) # endpoint=False로 설정 시 3 미만으로 바뀜

(array([2.  , 2.33, 2.67]), np.float64(0.3333333333333333))

In [341]:
(3-2)/3

0.3333333333333333

In [342]:
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

## numpy 주요 함수

### 내장함수 np.zeros()

In [343]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [344]:
np.zeros((5, ), dtype=int)

array([0, 0, 0, 0, 0])

In [345]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [346]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [347]:
np.zeros(2, 3)

TypeError: Cannot interpret '3' as a data type

### ones()

In [348]:
np.ones((2, 4)) # zeros()처럼 모두 실수 1.0인 배열을 반환함

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [349]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

### numpy.eye()

In [350]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [351]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [352]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [353]:
a = np.eye(3, 4, 1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [354]:
b = np.eye(3, 4, -1)
b

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

### numpy.full(shape, fill_value)

In [355]:
np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [356]:
np.full((2, 3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [357]:
np.full([2, 3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [358]:
np.full([2, 3], (1, 2)) # 갯수가 맞지 않아 오류남

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [359]:
np.arange(4).reshape(4, 1)

array([[0],
       [1],
       [2],
       [3]])

In [360]:
np.full((4, 3), np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

### numpy.empty(shape)

In [361]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [362]:
np.empty([2, 2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [363]:
np.empty([2, 3], dtype=int)

array([[   979578014,            0, 481036337261],
       [519691042932, 219043332136, 171798691881]])

## 배열 연산

In [364]:
a = np.arange(3)
a

array([0, 1, 2])

In [365]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [366]:
b = np.full_like(a, [1, 2, 3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [367]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [368]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [369]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [370]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [371]:
b += a
b

array([0.5, 2.5, 4.5, 6.5])

### 다양한 배열의 곱 연산자

In [372]:
a = np.full((2, 3), [1, 2, 3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [373]:
b = np.full((3, 2), [2, 1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [374]:
a @ b

array([[12,  6],
       [12,  6]])

In [375]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [376]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [377]:
import numpy as np
print(np.matmul(a, b))
print(np.matmul(b, a))

[[12  6]
 [12  6]]
[[3 6 9]
 [3 6 9]
 [3 6 9]]


### 배열 함수

#### a.sum()

In [378]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [379]:
a.sum()

np.int64(46)

In [380]:
a.sum(axis=0)

array([16, 30])

In [381]:
a.sum(axis=1)

array([30, 13,  3])

In [382]:
print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


#### a.cumsum()

In [383]:
a = np.array([[3, 5, 8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [384]:
# 일차원으로 펼쳐서 계산
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [385]:
a.cumsum(axis=0) # 시험예상, 행을 따라 세로로 합산

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [386]:
a.cumsum(axis=1) # 시험예상, 열을 따라 가로로 합산

array([[ 3,  8, 16],
       [ 1,  3,  6]])

### 다양한 이항 연산 범용 함수

In [387]:
a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [388]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [389]:
np.add(a, b)

array([ 3,  6, 11])

In [390]:
np.divide(a, b)

array([0.5, 2. , 4.5])

In [391]:
np.power(a, b)

array([ 1, 16, 81])

## 배열 슬라이싱과 형태 수정

### 1차원 배열의 첨자와 슬라이싱

In [392]:
a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [393]:
print(a[3])
print(a[-2])

9
64


In [394]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [395]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


### 역순과 대입

In [396]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [397]:
a[::-2]

array([81, 49, 25,  9,  1])

In [398]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [399]:
a[2:5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [400]:
a[2:5] = [-5, -5] # 대입될 원소가 3개 이어야 함.

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [401]:
a[2:5] = -10
a

array([  0,   1, -10, -10, -10,  25,  36,  49,  64,  81])

### 2차원 배열의 첨자와 슬라이싱

In [402]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [403]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [404]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [405]:
a[-2] # 동일 기능

array([18, 19, 20, 21, 22, 23])

In [406]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [407]:
a[-2, ]

array([18, 19, 20, 21, 22, 23])

In [408]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [409]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [410]:
a[, 1] # 행은 비우면 오류

SyntaxError: invalid syntax (1759013906.py, line 1)

In [411]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [412]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [413]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [414]:
a[2, 4]

np.int64(16)

In [415]:
a[2][4]

np.int64(16)

In [416]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [417]:
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [418]:
a[:, ]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [419]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [420]:
a[::-1, ::-1] # 행과 열을 모두 역순으로 바꾼 배열

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [421]:
# 마지막 행과 열을 제외한 배열 반환
a[:-1, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

### 3차원 배열의 첨자와 슬라이싱

In [422]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [423]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [424]:
a[: , 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [425]:
a[:, 1, 1]

array([ 5, 17])

In [426]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [427]:
a[..., 1] # = a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [428]:
a[1, ..., 1] # = a[1, :, 1]

array([13, 17, 21])

In [429]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [430]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 1차원 배열로 만드는 ndarray.ravel()

In [431]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [432]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### np.transpose(a)와 a.transpose(), a.T
#### 행과 열을 바꾼 전치 배열을 반환

In [433]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [434]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [435]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [436]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [437]:
# 3차원 배열의 전치 행렬
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [438]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

#### 두번째 인자로 조정하는 3차원의 전치 행렬
##### 시험에서 제외

In [439]:
np.transpose(b, (0, 1, 2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [440]:
np.transpose(b, (2, 1, 0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [441]:
np.transpose(b, (0, 2, 1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

#### np.swapaxes(a, axis1, axis2)

In [442]:
x = np.array([[7, 8, 9]])
x

array([[7, 8, 9]])

In [443]:
y = np.swapaxes(x, 0, 1)
y

array([[7],
       [8],
       [9]])

In [444]:
y = np.swapaxes(x, 1, 0)
y

array([[7],
       [8],
       [9]])

In [445]:
y[0, 0] = 10
y

array([[10],
       [ 8],
       [ 9]])

In [446]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [447]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [448]:
np.transpose(x, (2, 1, 0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

### 보기(view)

In [449]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [450]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [451]:
v[2] = 200

In [452]:
org

array([  0,   1, 200,   3,   4])

### 복사(copy)

In [453]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [454]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [455]:
c[2] = 200

In [456]:
org

array([0, 1, 2, 3, 4])

##### ndarray의 base 속성

In [457]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [458]:
y = x.reshape(2, 3) # view를 반환
y

array([[0, 1, 2],
       [3, 4, 5]])

In [459]:
print(x.base)

None


In [460]:
y.base

array([0, 1, 2, 3, 4, 5])

#### Ndarray: 같은 구조만 수정 가능

In [461]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [462]:
lst[3:5] = [30, 40, 50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [463]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [464]:
x[3:5] = [30, 40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [465]:
x[3:5] = [30, 40, 50] # 원래 원소가 2개인 배열 부분에 3개의 원소를 삽입하는 건 불가능
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

### 보기(뷰, view)와 얕은 복사

In [468]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [469]:
b = a
b is a

True

In [470]:
print(id(a))
print(id(b))

137692312613200
137692312613200


In [471]:
print(a.base)
print(b.base)

None
None


In [472]:
b[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [473]:
c = a.copy()
c

array([[100,   2,   3],
       [  4,   5,   6]])

In [474]:
print(id(a))
print(id(c))

137692312613200
137692312603120


In [475]:
print(c.base)

None


In [476]:
v = a.reshape(3, 2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [477]:
print(id(a))
print(id(v))

137692312613200
137692312608592


In [478]:
v[0, 1] = 200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [479]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])

## 브로드캐스팅

In [480]:
a = np.array([3, 4, 5])
b = np.array([8, 7, 6])
a + b

array([11, 11, 11])

In [481]:
a = np.array([3, 4, 5, 7])
b = np.array([8, 7, 6])
a * b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [482]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [483]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [484]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [485]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [486]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [487]:
y = arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [488]:
# 소수점 이하 자릿수를 2자리로 설정
np.set_printoptions(precision=2)

In [489]:
x / y

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [490]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [491]:
from numpy import arange

x = arange(1, 4)
x

array([1, 2, 3])

In [492]:
y = arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [493]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [494]:
x / y

array([[1.  , 2.  , 3.  ],
       [0.5 , 1.  , 1.5 ],
       [0.33, 0.67, 1.  ]])

In [495]:
from numpy import arange

x = arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [496]:
y = arange(1, 3)
y

array([1, 2])

In [497]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [498]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [499]:
import numpy as np
from numpy import array

x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [500]:
np.newaxis is None

True

In [501]:
# 차수를 증강
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [502]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [503]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [504]:
a.shape

(4, 1)

In [505]:
from numpy import array

a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [506]:
b = array([1, 2, 3])
b

array([1, 2, 3])

In [507]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [508]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

## 고급 색인

In [509]:
import numpy as np

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [510]:
print(x[1])

1


In [511]:
x[:5]

array([0, 1, 2, 3, 4])

In [512]:
x[ [2] ]

array([2])

In [513]:
x[[2, 3]]

array([2, 3])

In [514]:
x[ 2, 3 ] # error 발생

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [515]:
x[ [2, 3, 2, 5, 8] ]

array([2, 3, 2, 5, 8])

In [516]:
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [517]:
x[0, 1]

np.int64(1)

In [518]:
int(x[0, 1])

1

In [519]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [520]:
x[, 2:8]

SyntaxError: invalid syntax (664993225.py, line 1)

In [521]:
x[..., 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [522]:
x[0, 1]

np.int64(1)

In [523]:
x[ [0], [1] ] # 위의 코드와 다름

array([1])

In [524]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [525]:
x[ [0, 1] ]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [526]:
x[ [1, 3, 5] ]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [527]:
x[ [1, 3, 5], : ] # 위의 코드와 같음

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [528]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [529]:
x[ [1, 3] , [2, 2] ] # 매칭이 되어야 함. (1, 2), (3, 2) 위치의 배열

array([10, 26])

In [530]:
x[ [1, 3], [2] ]

array([10, 26])

In [531]:
x[ [1, 3], [2, 3] ] # (1, 2), (3, 3) 위치의 배열

array([10, 27])

In [532]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [533]:
x[ [0, 2, 4], [1] ]

array([ 1, 17, 33])

In [534]:
x[ [0, 2, 4], 1 ] # 대괄호 생략해도 됨

array([ 1, 17, 33])

In [535]:
x [ [0, 2, 4], :2 ]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [536]:
x[ [0, 2, 4], [1, 1, 1] ]

array([ 1, 17, 33])

In [537]:
x[ [0, 2, 4], [1, 1] ]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [538]:
a = np.arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [539]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [540]:
a[[2, 3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [541]:
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [542]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [543]:
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [544]:
a[np.arange(2, 4)][:, [1, 0]] # 1열 먼저 다음에 0열

array([[17, 16],
       [25, 24]])

In [545]:
a[np.arange(2, 4)][:, [1, 1, 1]]

array([[17, 17, 17],
       [25, 25, 25]])

In [546]:
a[np.arange(2, 4)][:, [1, 0, 3, 5]] # 1열, 0열, 3열, 5열 순

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [547]:
a[[2, 3]][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [548]:
a[[2, 3, 4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [549]:
a[np.arange(2, 5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [550]:
a[[2, 3, 4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [551]:
a[[2, 3, 4]][:, [-1, -2, -3, -4, -5 , -6, -7]]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

In [552]:
a[[2, 3, 4]][:, np.arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

### 종료