<a href="https://colab.research.google.com/github/Eun0416/2026-1-BDA/blob/main/code/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 다차원 배열 ndarray

In [1]:
import numpy as np

a = np.ndarray((2, 3))
a

array([[4.55258589e-315, 0.00000000e+000, 2.12199579e-314],
       [1.92208698e+227, 2.47938862e-091, 5.51006653e-310]])

In [2]:
import numpy as np

a = np.ndarray((3, 2), dtype=int)
a

array([[          921453643,                   0],
       [         4294967295, 8007464117033132328],
       [3251644510822034018,     111524988198974]])

In [4]:
a = np.ndarray((3, 2), int)
a

array([[      922773425,               0],
       [137693268676864,              33],
       [137693320772832, 137693320772832]])

## 내장함수 array()

In [9]:
import numpy as np

a = np.array([1, 2, 3], dtype=int)
a

array([1, 2, 3])

In [10]:
type(a)

numpy.ndarray

In [11]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [12]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


## 문자열 자료형

In [13]:
np.array([1, 'py', 3.14]) # 동일 자료형이 되어야 하기 때문에 문자열 자료형

array(['1', 'py', '3.14'], dtype='<U32')

In [14]:
import numpy as np
unicode_array = np.array(['가나다', '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사야자'], dtype='<U32')

In [15]:
unicode_array = np.array(['가나다라마'*7, '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라마바', '사아자'], dtype='<U32')

## numpy.arange()

In [16]:
import numpy as np

print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [17]:
import numpy as np

print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


## 배열의 모양을 바꾸는 reshape()

In [18]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [20]:
np.reshape(a, (3, 5)) # 원래 배열 원소가 12개 인데 원소가 15개(3, 5)라서 오류가 남

ValueError: cannot reshape array of size 12 into shape (3,5)

## 함수 linspace

In [30]:
import numpy as np
np.linspace(2, 3)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [31]:
(3-1)/(50-1)

0.04081632653061224

In [32]:
np.linspace(2, 3, 2)

array([2., 3.])

In [33]:
np.linspace(2, 3, 3)

array([2. , 2.5, 3. ])

In [34]:
np.linspace(2, 3, 3, retstep=True)

(array([2. , 2.5, 3. ]), np.float64(0.5))

In [36]:
a = np.linspace(2, 3, 3, retstep = True)
float(a[1])

0.5

In [40]:
np.linspace(2, 3, 3, retstep = True, endpoint=False) # endpoint=False로 설정 시 3 미만으로 바뀜

(array([2.        , 2.33333333, 2.66666667]), np.float64(0.3333333333333333))

In [41]:
(3-2)/3

0.3333333333333333

In [ ]:
np

## numpy 주요 함수

### 내장함수 np.zeros()

In [46]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [47]:
np.zeros((5, ), dtype=int)

array([0, 0, 0, 0, 0])

In [48]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [49]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.zeros(2, 3)

TypeError: Cannot interpret '3' as a data type

### ones()

In [64]:
np.ones((2, 4)) # zeros()처럼 모두 실수 1.0인 배열을 반환함

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

### numpy.eye()

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [53]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [54]:
a = np.eye(3, 4, 1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
b = np.eye(3, 4, -1)
b

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

### numpy.full(shape, fill_value)

In [57]:
np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [59]:
np.full((2, 3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [60]:
np.full([2, 3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [61]:
np.full([2, 3], (1, 2)) # 갯수가 맞지 않아 오류남

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [62]:
np.arange(4).reshape(4, 1)

array([[0],
       [1],
       [2],
       [3]])

In [63]:
np.full((4, 3), np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

### numpy.empty(shape)

In [67]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [68]:
np.empty([2, 2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [69]:
np.empty([2, 3], dtype=int)

array([[   976267268,            0, 472446402665],
       [481036337267, 468151435361,            0]])

## 배열 연산

In [70]:
a = np.arange(3)
a

array([0, 1, 2])

In [73]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
b = np.full_like(a, [1, 2, 3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [76]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [77]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [78]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [79]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [80]:
b += a
b

array([0.5, 2.5, 4.5, 6.5])

### 다양한 배열의 곱 연산자

In [83]:
a = np.full((2, 3), [1, 2, 3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [84]:
b = np.full((3, 2), [2, 1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [85]:
a @ b

array([[12,  6],
       [12,  6]])

In [86]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [87]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [89]:
import numpy as np
print(np.matmul(a, b))
print(np.matmul(b, a))

[[12  6]
 [12  6]]
[[3 6 9]
 [3 6 9]
 [3 6 9]]


### 배열 함수

#### a.sum()

In [91]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [92]:
a.sum()

np.int64(46)

In [93]:
a.sum(axis=0)

array([16, 30])

In [94]:
a.sum(axis=1)

array([30, 13,  3])

In [95]:
print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


#### a.cumsum()

In [96]:
a = np.array([[3, 5, 8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [97]:
# 일차원으로 펼쳐서 계산
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [98]:
a.cumsum(axis=0) # 시험예상, 행을 따라 세로로 합산

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [99]:
a.cumsum(axis=1) # 시험예상, 열을 따라 가로로 합산

array([[ 3,  8, 16],
       [ 1,  3,  6]])

### 다양한 이항 연산 범용 함수

In [100]:
a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [101]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [102]:
np.add(a, b)

array([ 3,  6, 11])

In [103]:
np.divide(a, b)

array([0.5, 2. , 4.5])

In [104]:
np.power(a, b)

array([ 1, 16, 81])

## 배열 슬라이싱과 형태 수정

### 1차원 배열의 첨자와 슬라이싱

In [105]:
a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [106]:
print(a[3])
print(a[-2])

9
64


In [107]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [108]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


### 역순과 대입

In [109]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [110]:
a[::-2]

array([81, 49, 25,  9,  1])

In [112]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [113]:
a[2:5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [114]:
a[2:5] = [-5, -5] # 대입될 원소가 3개 이어야 함.

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [115]:
a[2:5] = -10
a

array([  0,   1, -10, -10, -10,  25,  36,  49,  64,  81])

### 2차원 배열의 첨자와 슬라이싱

In [117]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [118]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [119]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [122]:
a[-2] # 동일 기능

array([18, 19, 20, 21, 22, 23])

In [120]:
a[-2, :]

array([18, 19, 20, 21, 22, 23])

In [121]:
a[-2, ]

array([18, 19, 20, 21, 22, 23])

In [123]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [124]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [125]:
a[, 1] # 행은 비우면 오류

SyntaxError: invalid syntax (3063698125.py, line 1)

In [126]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [127]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [128]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [129]:
a[2, 4]

np.int64(16)

In [130]:
a[2][4]

np.int64(16)

In [131]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [132]:
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [133]:
a[:, ]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [134]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [135]:
a[::-1, ::-1] # 행과 열을 모두 역순으로 바꾼 배열

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [136]:
# 마지막 행과 열을 제외한 배열 반환
a[:-1, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

### 3차원 배열의 첨자와 슬라이싱

In [137]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [138]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [139]:
a[: , 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [140]:
a[:, 1, 1]

array([ 5, 17])

In [141]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [142]:
a[..., 1] # = a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [143]:
a[1, ..., 1] # = a[1, :, 1]

array([13, 17, 21])

In [144]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 1차원 배열로 만드는 ndarray.ravel()

In [147]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [148]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### np.transpose(a)와 a.transpose(), a.T
#### 행과 열을 바꾼 전치 배열을 반환

In [149]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [150]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [151]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [152]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [155]:
# 3차원 배열의 전치 행렬
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [156]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

#### 두번째 인자로 조정하는 3차원의 전치 행렬
##### 시험에서 제외

In [157]:
np.transpose(b, (0, 1, 2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [158]:
np.transpose(b, (2, 1, 0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [159]:
np.transpose(b, (0, 2, 1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

#### np.swapaxes(a, axis1, axis2)

In [160]:
x = np.array([[7, 8, 9]])
x

array([[7, 8, 9]])

In [162]:
y = np.swapaxes(x, 0, 1)
y

array([[7],
       [8],
       [9]])

In [163]:
y = np.swapaxes(x, 1, 0)
y

array([[7],
       [8],
       [9]])

In [165]:
y[0, 0] = 10
y

array([[10],
       [ 8],
       [ 9]])

In [166]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [167]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [168]:
np.transpose(x, (2, 1, 0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

### 보기(view)

In [169]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [170]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [171]:
v[2] = 200

In [172]:
org

array([  0,   1, 200,   3,   4])

### 복사(copy)

In [254]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [255]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [256]:
c[2] = 200

In [257]:
org

array([0, 1, 2, 3, 4])

##### ndarray의 base 속성

In [271]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [273]:
y = x.reshape(2, 3) # view를 반환
y

array([[0, 1, 2],
       [3, 4, 5]])

In [274]:
print(x.base)

None


In [275]:
y.base

array([0, 1, 2, 3, 4, 5])

#### Ndarray: 같은 구조만 수정 가능

## 브로드캐스팅

In [173]:
a = np.array([3, 4, 5])
b = np.array([8, 7, 6])
a + b

array([11, 11, 11])

In [174]:
a = np.array([3, 4, 5, 7])
b = np.array([8, 7, 6])
a * b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [175]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [176]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [177]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [178]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [179]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [180]:
y = arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [181]:
# 소수점 이하 자릿수를 2자리로 설정
np.set_printoptions(precision=2)

In [182]:
x / y

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [183]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [184]:
from numpy import arange

x = arange(1, 4)
x

array([1, 2, 3])

In [185]:
y = arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [186]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [187]:
x / y

array([[1.  , 2.  , 3.  ],
       [0.5 , 1.  , 1.5 ],
       [0.33, 0.67, 1.  ]])

In [188]:
from numpy import arange

x = arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [189]:
y = arange(1, 3)
y

array([1, 2])

In [190]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [191]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [192]:
import numpy as np
from numpy import array

x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [193]:
np.newaxis is None

True

In [194]:
# 차수를 증강
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [195]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [196]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [197]:
a.shape

(4, 1)

In [198]:
from numpy import array

a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [202]:
b = array([1, 2, 3])
b

array([1, 2, 3])

In [203]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [204]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

## 고급 색인

In [205]:
import numpy as np

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [206]:
print(x[1])

1


In [207]:
x[:5]

array([0, 1, 2, 3, 4])

In [210]:
x[ [2] ]

array([2])

In [211]:
x[[2, 3]]

array([2, 3])

In [214]:
x[ 2, 3 ] # error 발생

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [215]:
x[ [2, 3, 2, 5, 8] ]

array([2, 3, 2, 5, 8])

In [216]:
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [217]:
x[0, 1]

np.int64(1)

In [218]:
int(x[0, 1])

1

In [219]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [220]:
x[, 2:8]

SyntaxError: invalid syntax (664993225.py, line 1)

In [221]:
x[..., 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [222]:
x[0, 1]

np.int64(1)

In [231]:
x[ [0], [1] ] # 위의 코드와 다름

array([1])

In [232]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [233]:
x[ [0, 1] ]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [234]:
x[ [1, 3, 5] ]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [235]:
x[ [1, 3, 5], : ] # 위의 코드와 같음

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [237]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [238]:
x[ [1, 3] , [2, 2] ] # 매칭이 되어야 함. (1, 2), (3, 2) 위치의 배열

array([10, 26])

In [240]:
x[ [1, 3], [2] ]

array([10, 26])

In [241]:
x[ [1, 3], [2, 3] ] # (1, 2), (3, 3) 위치의 배열

array([10, 27])

In [242]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [243]:
x[ [0, 2, 4], [1] ]

array([ 1, 17, 33])

In [246]:
x[ [0, 2, 4], 1 ] # 대괄호 생략해도 됨

array([ 1, 17, 33])

In [247]:
x [ [0, 2, 4], :2 ]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [248]:
x[ [0, 2, 4], [1, 1, 1] ]

array([ 1, 17, 33])

In [249]:
x[ [0, 2, 4], [1, 1] ]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [250]:
a = np.arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [251]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [252]:
a[[2, 3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [253]:
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [258]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [259]:
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [261]:
a[np.arange(2, 4)][:, [1, 0]] # 1열 먼저 다음에 0열

array([[17, 16],
       [25, 24]])

In [262]:
a[np.arange(2, 4)][:, [1, 1, 1]]

array([[17, 17, 17],
       [25, 25, 25]])

In [263]:
a[np.arange(2, 4)][:, [1, 0, 3, 5]] # 1열, 0열, 3열, 5열 순

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [264]:
a[[2, 3]][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [265]:
a[[2, 3, 4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [266]:
a[np.arange(2, 5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [267]:
a[[2, 3, 4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [268]:
a[[2, 3, 4]][:, [-1, -2, -3, -4, -5 , -6, -7]]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

In [270]:
a[[2, 3, 4]][:, np.arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

### 종료