<a href="https://colab.research.google.com/github/Eun0416/2026-1-BDA/blob/main/code/04w_array_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 04 다차원 배열 결합과 분리

## 배열 결합

### numpy.vstack

In [1]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [5]:
np.hstack((a, b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [6]:
x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

### numpy.hstack()

In [7]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [9]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [10]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

### numpy.column_stack

In [11]:
x = np.array((1, 2, 3))
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [12]:
x[: np.newaxis]

array([1, 2, 3])

In [13]:
x = np.array((1, 2, 3))
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [14]:
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [15]:
np.column_stack == np.hstack

False

### numpy.row_stack()

In [34]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [36]:
np.row_stack((a, b))

/tmp/ipykernel_1340/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

### numpy.concatenate()

In [37]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

In [38]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6])

In [39]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [40]:
# 1차 배열인 경우 axis와 동일
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [41]:
# 2차원 배열 결합
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [44]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [45]:
np.concatenate((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [46]:
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [48]:
np.concatenate((x, y, z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [49]:
# 평면화 작업 후 연결
np.concatenate((x, y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

### np.stack()

In [50]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [51]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [52]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
np.stack((a, b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [57]:
# 3차원 배열
np.arange(1, 19).reshape(3, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [58]:
# 3차원 배열
np.arange(16).reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [59]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [60]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [61]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [62]:
ax0 = np.stack((x, y, z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [63]:
ax0.shape

(3, 2, 3)

In [64]:
ax1 = np.stack((x, y, z), axis = 1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [65]:
ax1.shape

(2, 3, 3)

In [66]:
ax2 = np.stack((x, y, z), axis = 2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [67]:
ax2.shape

(2, 3, 3)

In [68]:
print(x, '\n')
print(y, '\n')
print(z, '\n')

[[0 1 2]
 [3 4 5]] 

[[10 11 12]
 [13 14 15]] 

[[20 21 22]
 [23 24 25]] 



In [69]:
print('np.stack((x, y, z), axis=0)')
print(np.stack((x, y, z), axis=0))
print('np.stack((x, y, z), axis=1)')
print(np.stack((x, y, z), axis=1))
print('np.stack((x, y, z), axis=2)')
print(np.stack((x, y, z), axis=2))

np.stack((x, y, z), axis=0)
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]
np.stack((x, y, z), axis=1)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]
np.stack((x, y, z), axis=2)
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]


In [70]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [71]:
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [72]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [73]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [74]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [75]:
np.expand_dims(y, axis=2)

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [76]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [77]:
z[:, :, np.newaxis]

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [78]:
np.expand_dims(z, axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [79]:
np.stack((x, y, z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

### column_stack()과 hstack()

In [17]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
c = np.arange(1, 6, 2)
c

array([1, 3, 5])

In [21]:
np.hstack((a, np.expand_dims(c, axis=1))) # 늘리지 않으면 오류남

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [22]:
np.column_stack( (a, c) )

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

### np.c_[]

In [23]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
np.column_stack( (a, b) )

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])
x

array([[1, 2, 3]])

In [26]:
y

array([[4, 5, 6]])

In [27]:
x.shape, y.shape

((1, 3), (1, 3))

In [30]:
np.column_stack( (x, y) )

array([[1, 2, 3, 4, 5, 6]])

In [31]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [32]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [33]:
np.column_stack( (x, 10, 20, y) )

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

### np.r_[]

In [80]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [81]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [82]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [83]:
np.row_stack((a, b))

/tmp/ipykernel_1340/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [85]:
np.r_[3:10:3, [0]*2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [86]:
np.r_[-1:1:6j, [0]*2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [87]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [88]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [89]:
np.r_[a, a, a] # concetenate along first axis

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [90]:
np.r_['0', a, a] # concetenate along first axis

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [91]:
np.r_['-1', a, a] # concetenate along first axis

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [92]:
np.r_['1', a, a] # concetenate along first axis

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

## 배열 분리

### np.split(ary)

In [93]:
import numpy as np

x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [94]:
s = np.split(x, 3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [95]:
y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [96]:
np.split(y, [2, 3, 4, 6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [97]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
np.split(x, [2, 6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [100]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [101]:
np.split(a, 3, axis=1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [103]:
np.hsplit(a, 3) # 위와 동일

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [102]:
np.split(a, 4, axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [104]:
b = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [105]:
np.split(b, 3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [106]:
np.split(b, [2, 4, 6], axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

In [107]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [108]:
np.split(a, [3, 5, 7], axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [109]:
b = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [110]:
np.split(b, 3, axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

### np.hsplit

In [111]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [113]:
np.hsplit(a, [2, 5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [114]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [115]:
np.hsplit(a, (3, 5, 8))

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [116]:
a[:, :3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [117]:
a[:, 8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

### np.vsplit

In [118]:
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [119]:
np.vsplit(a, 3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [120]:
np.vsplit(a, 4) # 나누어지지 않아 오류 발생

ValueError: array split does not result in an equal division

In [125]:
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [126]:
np.vsplit(a, (1, 4, 6))

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [127]:
a[:1, :]

array([[0, 1, 2]])

In [128]:
a[4:6, :]

array([[12, 13, 14],
       [15, 16, 17]])

In [131]:
# 3차원 배열
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [132]:
np.split(x, 2, axis=0)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [133]:
np.vsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]]),
 array([[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],
 
        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [135]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [136]:
np.vsplit(x, [1, 3])

[array([[[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]]),
 array([[[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],
 
        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]),
 array([[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]])]

In [137]:
x[:1, :, :]

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [138]:
x[1:3]

array([[[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [139]:
x[3:]

array([[[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [140]:
# 3차원 배열 hsplit
x = np.arange(32).reshape(4, 4, 2)

In [141]:
np.hsplit(x, 2)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [142]:
np.split(x, 2, axis=1)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[16, 17],
         [18, 19]],
 
        [[24, 25],
         [26, 27]]]),
 array([[[ 4,  5],
         [ 6,  7]],
 
        [[12, 13],
         [14, 15]],
 
        [[20, 21],
         [22, 23]],
 
        [[28, 29],
         [30, 31]]])]

In [144]:
x = np.arange(32).reshape(4, 4, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [145]:
np.hsplit(x, [1, 3])

[array([[[ 0,  1]],
 
        [[ 8,  9]],
 
        [[16, 17]],
 
        [[24, 25]]]),
 array([[[ 2,  3],
         [ 4,  5]],
 
        [[10, 11],
         [12, 13]],
 
        [[18, 19],
         [20, 21]],
 
        [[26, 27],
         [28, 29]]]),
 array([[[ 6,  7]],
 
        [[14, 15]],
 
        [[22, 23]],
 
        [[30, 31]]])]

## numpy의 난수와 다양한 함수

### 난수 제너레이터의 함수 random()

In [151]:
import numpy as np

rg = np.random.default_rng(12345) # 시드값
rg.random() # [0, 1) → 0 이상 1미만

0.22733602246716966

In [156]:
rg = np.random.default_rng(1)
rg.random()

0.5118216247002567

In [154]:
rg.random()

0.6762546707509746

In [157]:
rg.random(5)

array([0.9504637 , 0.14415961, 0.94864945, 0.31183145, 0.42332645])

In [158]:
rg.random( (3, 4) )

array([[0.82770259, 0.40919914, 0.54959369, 0.02755911],
       [0.75351311, 0.53814331, 0.32973172, 0.7884287 ],
       [0.30319483, 0.45349789, 0.1340417 , 0.40311299]])

In [159]:
rg.random( (2, 3, 4) )

array([[[0.20345524, 0.26231334, 0.75036467, 0.28040876],
        [0.48519097, 0.9807372 , 0.96165719, 0.72478994],
        [0.54122686, 0.2768912 , 0.16065201, 0.96992541]],

       [[0.51606859, 0.11586561, 0.62348976, 0.77668311],
        [0.6130033 , 0.9172977 , 0.03959288, 0.52858926],
        [0.45933588, 0.06234958, 0.64132817, 0.85263284]]])

In [ ]:
rg.random(5)

array([0.9504637 , 0.14415961, 0.94864945, 0.31183145, 0.42332645])

In [160]:
rg.random(5)

array([0.59294102, 0.26009745, 0.83988152, 0.50949588, 0.51088888])

### integers()

In [163]:
import numpy as np

rg = np.random.default_rng(1)
rg.integers(low=0, high=10, size=3) # [0, 10) 정수 난수

array([4, 5, 7])

In [169]:
rg.integers(0, high=20, size=(3, 4))

array([[14,  5, 10, 18],
       [ 5, 14,  3,  6],
       [19,  8, 10,  5]])

In [171]:
rg.integers(1, 7, (3, 4))

array([[1, 3, 4, 3],
       [5, 3, 4, 5],
       [6, 3, 1, 5]])

### standard_norml()

In [172]:
import numpy as np

rg = np.random.default_rng(1)
rg.standard_normal(3) # 표준 정규 분포 실수 난수

array([0.34558419, 0.82161814, 0.33043708])

In [183]:
rg.standard_normal((3, 4)) # 표준 정규 분포 실수 난수

array([[ 0.61687876,  2.54789782, -1.00092485, -1.25069576],
       [ 0.58896893, -0.84072159, -0.50602548, -0.34811747],
       [ 0.53200209, -0.40530236,  0.27788284, -0.17653326]])

In [ ]:
"""
 -1 ~ 1 68%
 -2 ~ 2 95%
 -3 ~ 3 99.7%
"""

In [184]:
rg.standard_normal(5)

array([-0.8446711 , -0.31982626, -0.95039967,  0.00651499, -1.12386623])

## 배열 결합 연습

In [187]:
a = np.arange(1, 4)
b = np.arange(4, 7)
c = np.arange(7, 10)
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [188]:
p = np.arange(1, 7).reshape(2, 3)
q = np.arange(11, 17).reshape(2, 3)
r = np.arange(21, 27).reshape(2, 3)
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [190]:
np.vstack( (a, b, c) ) # 1D → 2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [192]:
np.vstack( (p, q, r) ) # 2D → 2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [193]:
np.hstack( (a, b, c) ) # 1D → 1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [194]:
np.hstack( (p, q, r) ) # 2D → 2D

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [195]:
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [196]:
np.column_stack((a, b, c)) # 1D → 2D

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [197]:
np.column_stack((p, q, r)) # 2D → 2D

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [198]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [200]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [201]:
np.concatenate((a, b, c), axis=1) # 1차원에는 축이 존재하지 않음

AxisError: axis 1 is out of bounds for array of dimension 1

In [202]:
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [204]:
np.concatenate((a, b, c), axis=-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [208]:
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [206]:
np.concatenate((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [207]:
np.concatenate((p, q, r), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [209]:
np.concatenate((p, q, r), axis=1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [210]:
np.concatenate((p, q, r), axis=-1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [211]:
np.concatenate((p, q, r), axis=None) # 1차원으로 나열해줌

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [213]:
np.c_[a, b, c] # 1D → 2D # 괄호 잘 안씀

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [214]:
np.column_stack( (a, b, c) ) # 1D → 2D

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [215]:
np.column_stack( a, b, c ) # 리스트나 튜플 형태로 묶어야 함.

TypeError: column_stack() takes 1 positional argument but 3 were given

In [216]:
np.c_[p, q, r] # 2D → 2D

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [218]:
np.r_[a, b, c] # 1D → 1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [219]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [220]:
np.r_[p, q, r]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [224]:
np.vstack((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

# 종료